### ISSUE TITLE
Github page link is redirecting somewhere else

### ISSUE THREAD

**Issue by HazzazBinFaiz** [iqbalhasandev/laravel-bulksmsbd#2]
Th link provided in description is redirecting to an other url, **https://jannatul.me/laravel-bulksmsbd/**

Preview:
![image](https://user-images.githubusercontent.com/29161993/161383148-9f598a19-16bb-453c-bee1-352218bab59e.png)

Is this a mistake or I am looking for documentation in wrong url ?

**Comment by iqbalhasandev** [comment]
# This package is abandoned and no longer maintained. The author suggests using the <a href="https://github.com/nanopkg/laravel-bulk-sms-bd">nanopkg/laravel-bulk-sms-bd</a> package instead.
